---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boottttttttttttt
  labels:
    app: boottttttttttttt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boottttttttttttt
  template:
    metadata:
      labels:
        app: boottttttttttttt
    spec:
      containers:
        - name: boottttttttttttt
          image: docker.io/phengbunath/boottttttttttttt:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
